// Generated by https://quicktype.io

export interface Country {
  flags: Flags;
  name: Name;
  capital: string[];
  region: string;
  population: number;
}

interface Flags {
  png: string;
  svg: string;
  alt: string;
}

interface Name {
  common: string;
  official: string;
  nativeName: NativeName;
}

interface NativeName {
  eng: Eng;
  smo: Eng;
}

interface Eng {
  official: string;
  common: string;
}
