import { ThemeProvider } from "@/provider/theme-provider";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import QueryProvider from "@/provider/query-provider";
import { Navbar } from "@/components/ui/navbar";

const nunito = Nunito_Sans({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Countries App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${nunito.className} `}>
        <QueryProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <main className="flex min-h-screen w-full flex-col bg-light-gray dark:bg-bg-darkest-blue">
              <Navbar />
              {children}
            </main>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
